### ISSUE TITLE
DB cannot be accessed by multiple processes

### ISSUE THREAD

**Issue by askryanlee** [Ivshti/linvodb3#23]
When I try to connect to the DB with the 2nd app, I get an error:

OpenError: IO error: lock /home/ryan/node/maxscrafts/app/linvodb3/Users/LOCK: Resource temporarily unavailable
    at .../node_modules/linvodb3/node_modules/levelup/lib/levelup.js:119:34
    at .../node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16

code:
new LinvoDB(schema.name, schema.schema, {
   filename: path.join(root_dir, "app/linvodb3", schema.name)
}),

**Comment by Ivshti** [comment]
linvodb runs over a key/value store as a backend, so it's an issue in the store rather than linvodb itself.

Most stores like level and Medea do not allow access from multiple processes, but there may be some store that can - but that brings all kinds of other issues, like keeping the indexes in sync.

What is the use case?

**Comment by askryanlee** [comment]
Cool. I see your point.

**Comment by chovy** [comment]
I don't understand how you can have a database that can't be read from while another process is writing to it. This is completely useless to me.

What am I missing?

**Comment by acao** [comment]
@chovy look into [medea-clusterify](https://github.com/medea/medea-clusterify) and also [multilevel](https://www.npmjs.com/package/multilevel), etc. It seems that a lot of folks are running multiprocess level databases, just takes a little extra configuration. 'level compatible' leaves open a lot of options!
