### ISSUE TITLE
Any plans to rewrite on ES6?

### ISSUE THREAD

**Issue by c58** [Ivshti/linvodb3#24]

**Comment by Ivshti** [comment]
Yes, as the models especially will benefit a lot from using ES6 features. Other than that, I see no large benefit. With this, I'd like to link this issue: https://github.com/Ivshti/linvodb3/issues/21, as both would probably happen at the same time

**Comment by c58** [comment]
I've decided to reimplement almost all things of the project with better decomposition, promises, ES6 and code linting. Check my work in https://github.com/c58/marsdb 
Maybe it would be useful for you. It does not work yet, i will continue working on it at free time. I'm planning to finish in next two weeks.

**Comment by Ivshti** [comment]
This seems like it has the potential to become the more elegant and lean version of linvodb, please keep us posted in this thread!

**Comment by c58** [comment]
Hey, checkout my progress :) https://github.com/c58/marsdb
Indexes is removed, but should be implemented soon, after some storage implementations (just in-memory now)

**Comment by Ivshti** [comment]
@c58 I am keeping an eye on it, and I like the direction it's going in, especially under the hood. I was thinking of ways to do indexes better. Currently linvodb creates indexes for every key individually, on demand, and on queries makes an intersection of results from separate indexes.

I like that approach very much, but intersections can become expensive. The other option is to put results in a bitmap and XOR / XAND according to the required logic, but that will get ugly quickly when exceeding a million records. If there are clearly defined goals though, as with linvodb - "embedded DB engine for desktop apps" - then it's OK. But I'm still concerned about a possible desktop use case where there are a lot of records.

The other option is using compound indexes, but that can also get ugly quickly with many queries and etc. Maybe the DB can make compound indexes only in certain conditions and re-use them for several different queries, but I'm reluctant of trying to make a DB engine "smart". It's not a sustainable approach.

Thinking to other DB engines, embedded or not, relational or not, I cannot think of a solution to this problem. Maybe Postgres / some MySQL storage engines have the answer within them, but unfortunately I do not have enough knowledge on the matter.

Any ideas?

**Comment by c58** [comment]
I think we need to get some ideas from the original, likely it's open sourced (I mean MongoDB, ofc) :) 
Also I found some mongo-like databases, like TingoDB, whose supports indexes, but I don't think it uses some better solution, then intersecting/XORing. (need to be checked)

And some words about millions of records. It is not my case but I agree that using indexes with some simple query keys, like {a: 'test'}, is awesome, especially if it would work with simple regexp patterns, like "^test", just like meteor does.

So, I'm planing to make an algorithm of matching consisting of three stages:
1. Preprocess query for extracting simple indexable cases (no arrays, only numeric bounds and texts with simple regexes). Ensure indexes on demand and get list of ids.
2. Get objects from storage by given ids
3. If preprocessed query is still contains some query keys, match retrieved documents with minimingo algorithm

It would be enough for me. Also it should be benchmarked and compared with another solutions for discussing about performance.

**Comment by Ivshti** [comment]
That's exactly the issue, _the original_ doesn't solve the problem at all. It relies on you to make your own indexes, which is totally **ok**, but then it picks which indexes to use in a totally mindless way - if you have a lot of indexes. Which leads to having to use .hint(), which kind of removes the whole advantage of it's promised ease of use. You can optimize queries greatly with .hint(), but if you have a more dynamic query (e.g. not always on the same properties), then you have to be smart about hints.

MongoDB is also built to do one index lookup for a query. I'm not entirely sure if today it still follows that, but I'm sure it does a lot of scanning if you haven't optimized the queries.

That's why linvodb is entirely scan-less, except of course the first time when indexes are built.

Maybe some manual intervention should be allowed, but instead of building indexes prematurely, just give them as .hint()'s and then the DB first lookups this index, no matter if compound or not, and then applies XOR/XAND with the other matches for other properties if there are any.
