### ISSUE TITLE
Preloading db

### ISSUE THREAD

**Issue by Koncopd** [Ivshti/linvodb3#39]
Is it possible to preload db before quering? Like netdb.loadDatabase?

**Comment by Ivshti** [comment]
It doesn't need .loadDatabase, because the architecture is different

1. storage decides whether to pre-load key/value pairs
2. storage almost certainly preloads keys
3. as for in-memory indexes, they are built on demand

if you want to build all your indexes on demand, just specify ``index: true`` in your model for every queried property
